@startuml
start
:解析接收到的选举请求消息;

:获取当前节点的最后日志信息;

if (接收到的任期 > 当前任期\n且请求的最后日志任期 >= 当前最后日志任期) then (是)
    :更新当前任期;
    :切换到Follower状态;
    :为请求的候选人投票;
    :构建投票成功的响应消息;
    :发送响应消息到请求的候选人;
    :打印投票信息;
    :返回True;
else (否)
    :返回False;
endif

stop
@enduml
