@startuml
start
:判断数据是否为空;

if (数据为空) then (是(心跳，超时发送))
    :获取最后一个日志的索引和任期;
    :构建心跳检测消息;
    :广播心跳检测到所有其他节点;
    :打印心跳检测发送信息;
else (否(日志追加))
    :构建新的日志条目;
    :追加到本地日志;
    :获取最新日志的索引和任期;
    :构建日志追加消息;
    :广播日志追加消息到所有其他节点;
    :返回True;
endif

stop
@enduml
